version: '3'

services:
  server:
    container_name: grpc-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        WWWGROUP: '${WWWGROUP:-1001}'
    image: grpc-server
    networks:
      - grpc-test
  client:
    container_name: grpc-client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        WWWGROUP: '${WWWGROUP:-1001}'
    image: grpc-client
    volumes:
    - './client:/var/www/html'
    networks:
      - grpc-test

networks:
  grpc-test:
    driver: bridge
