version: '3'

services:
  server:
    container_name: grpc-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        WWWGROUP: '${WWWGROUP:-1001}'
    image: grpc-server
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8081:8081'
    networks:
      - grpc-test
  # client:
  #   container_name: grpc-client
  #   build:
  #     context: ./src/client
  #     dockerfile: ./src/client/Dockerfile
  #     args:
  #       WWWGROUP: '${WWWGROUP:-1001}'
  #   image: grpc-client
  #   networks:
  #     - grpc-test

networks:
  grpc-test:
    driver: bridge
