// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoServicesClient is the client API for TodoServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoServicesClient interface {
	Add(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error)
}

type todoServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoServicesClient(cc grpc.ClientConnInterface) TodoServicesClient {
	return &todoServicesClient{cc}
}

func (c *todoServicesClient) Add(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, "/todo.TodoServices/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServicesServer is the server API for TodoServices service.
// All implementations must embed UnimplementedTodoServicesServer
// for forward compatibility
type TodoServicesServer interface {
	Add(context.Context, *TodoRequest) (*TodoResponse, error)
	mustEmbedUnimplementedTodoServicesServer()
}

// UnimplementedTodoServicesServer must be embedded to have forward compatible implementations.
type UnimplementedTodoServicesServer struct {
}

func (UnimplementedTodoServicesServer) Add(context.Context, *TodoRequest) (*TodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedTodoServicesServer) mustEmbedUnimplementedTodoServicesServer() {}

// UnsafeTodoServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoServicesServer will
// result in compilation errors.
type UnsafeTodoServicesServer interface {
	mustEmbedUnimplementedTodoServicesServer()
}

func RegisterTodoServicesServer(s grpc.ServiceRegistrar, srv TodoServicesServer) {
	s.RegisterService(&TodoServices_ServiceDesc, srv)
}

func _TodoServices_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServicesServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoServices/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServicesServer).Add(ctx, req.(*TodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoServices_ServiceDesc is the grpc.ServiceDesc for TodoServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoServices",
	HandlerType: (*TodoServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _TodoServices_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
