// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TervicesClient is the client API for Tervices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TervicesClient interface {
	Add(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error)
}

type tervicesClient struct {
	cc grpc.ClientConnInterface
}

func NewTervicesClient(cc grpc.ClientConnInterface) TervicesClient {
	return &tervicesClient{cc}
}

func (c *tervicesClient) Add(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, "/todo.Tervices/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TervicesServer is the server API for Tervices service.
// All implementations must embed UnimplementedTervicesServer
// for forward compatibility
type TervicesServer interface {
	Add(context.Context, *TodoRequest) (*TodoResponse, error)
	mustEmbedUnimplementedTervicesServer()
}

// UnimplementedTervicesServer must be embedded to have forward compatible implementations.
type UnimplementedTervicesServer struct {
}

func (UnimplementedTervicesServer) Add(context.Context, *TodoRequest) (*TodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedTervicesServer) mustEmbedUnimplementedTervicesServer() {}

// UnsafeTervicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TervicesServer will
// result in compilation errors.
type UnsafeTervicesServer interface {
	mustEmbedUnimplementedTervicesServer()
}

func RegisterTervicesServer(s grpc.ServiceRegistrar, srv TervicesServer) {
	s.RegisterService(&Tervices_ServiceDesc, srv)
}

func _Tervices_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TervicesServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Tervices/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TervicesServer).Add(ctx, req.(*TodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tervices_ServiceDesc is the grpc.ServiceDesc for Tervices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tervices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.Tervices",
	HandlerType: (*TervicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Tervices_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
